// @license
// Copyright (c) Audanika
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// Generated from src/aud_midi_windows.h by ffigen.yaml, do not edit.
// Windows only: the code asset exists on Windows alone.
// coverage:ignore-file
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:aud_midi_windows/aud_midi_windows_shim')
library;

import 'dart:ffi' as ffi;

/// Starts to pair the Bluetooth LE device address; the result follows as
/// BLE_PAIR_COMPLETED carrying request. Paired BLE-MIDI devices appear as
/// WinRT MIDI 1.0 ports.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<amw_context>, ffi.Int64, ffi.Uint64)
>()
external int amw_ble_pair(
  ffi.Pointer<amw_context> context,
  int request,
  int address,
);

/// Starts to scan for BLE-MIDI peripherals; findings follow as
/// BLE_ADVERTISEMENT events.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<amw_context>)>()
external int amw_ble_scan_start(ffi.Pointer<amw_context> context);

/// Stops the scan.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<amw_context>)>()
external int amw_ble_scan_stop(ffi.Pointer<amw_context> context);

/// Starts to unpair the Bluetooth LE device address; the result follows as
/// BLE_UNPAIR_COMPLETED carrying request.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<amw_context>, ffi.Int64, ffi.Uint64)
>()
external int amw_ble_unpair(
  ffi.Pointer<amw_context> context,
  int request,
  int address,
);

/// Returns the native monotonic clock (QueryPerformanceCounter) in
/// microseconds; all record times use this clock.
@ffi.Native<ffi.Int64 Function()>()
external int amw_clock_now_us();

/// Creates a context, starts its worker thread and detects the features.
/// signal is called whenever events or data are waiting.
@ffi.Native<
  ffi.Int32 Function(amw_signal_fn, ffi.Pointer<ffi.Pointer<amw_context>>)
>()
external int amw_create(
  amw_signal_fn signal,
  ffi.Pointer<ffi.Pointer<amw_context>> context,
);

/// Stops watchers and scans, closes all ports, joins the worker thread,
/// waits until no callback is running and frees the context. The signal
/// function is not called after this returns.
@ffi.Native<ffi.Void Function(ffi.Pointer<amw_context>)>()
external void amw_destroy(ffi.Pointer<amw_context> context);

/// Returns the AMW_FEATURE_* bits detected by amw_create.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<amw_context>)>()
external int amw_features(ffi.Pointer<amw_context> context);

/// Copies the UTF-8 message of the last failure on the calling thread into
/// buffer and returns its full length in bytes, which may exceed capacity.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Uint8>, ffi.Int32)>()
external int amw_last_error(ffi.Pointer<ffi.Uint8> buffer, int capacity);

/// Closes the port handle; its records are discarded.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<amw_context>, ffi.Int32)>()
external int amw_port_close(ffi.Pointer<amw_context> context, int handle);

/// Starts to open the port id (UTF-8, id_length bytes) as kind
/// (AMW_KIND_*). The result follows as OPEN_COMPLETED carrying request.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<amw_context>,
    ffi.Int64,
    ffi.Pointer<ffi.Uint8>,
    ffi.Int32,
    ffi.Int32,
  )
>()
external int amw_port_open(
  ffi.Pointer<amw_context> context,
  int request,
  ffi.Pointer<ffi.Uint8> id,
  int id_length,
  int kind,
);

/// Moves as many whole data records of the input handle as fit into buffer
/// and stores their length in length; dropped receives the number of
/// messages lost since the last read because the port's buffer was full.
/// Returns AMW_E_BUFFER_TOO_SMALL with the size of the next record in
/// length when not even that one fits.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<amw_context>,
    ffi.Int32,
    ffi.Pointer<ffi.Uint8>,
    ffi.Int32,
    ffi.Pointer<ffi.Int32>,
    ffi.Pointer<ffi.Int64>,
  )
>()
external int amw_port_read(
  ffi.Pointer<amw_context> context,
  int handle,
  ffi.Pointer<ffi.Uint8> buffer,
  int capacity,
  ffi.Pointer<ffi.Int32> length,
  ffi.Pointer<ffi.Int64> dropped,
);

/// Sends length bytes of data to the output handle: MIDI 1.0 bytes for
/// AMW_KIND_MIDI1_OUT, complete UMPs as 32-bit words for UMP kinds. due_us
/// is the native time in microseconds at which a UMP port delivers the
/// data; 0 sends at once. MIDI 1.0 ports always send at once.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<amw_context>,
    ffi.Int32,
    ffi.Pointer<ffi.Uint8>,
    ffi.Int32,
    ffi.Int64,
  )
>()
external int amw_port_send(
  ffi.Pointer<amw_context> context,
  int handle,
  ffi.Pointer<ffi.Uint8> data,
  int length,
  int due_us,
);

/// Moves as many whole events as fit into buffer and stores their length in
/// length, 0 when no event waits. Returns AMW_E_BUFFER_TOO_SMALL with the
/// size of the next event in length when not even that one fits.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<amw_context>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Int32,
    ffi.Pointer<ffi.Int32>,
  )
>()
external int amw_read_events(
  ffi.Pointer<amw_context> context,
  ffi.Pointer<ffi.Uint8> buffer,
  int capacity,
  ffi.Pointer<ffi.Int32> length,
);

/// Allows the next signal. Call it before draining the buffers.
@ffi.Native<ffi.Void Function(ffi.Pointer<amw_context>)>()
external void amw_rearm(ffi.Pointer<amw_context> context);

/// Returns AMW_VERSION of the built shim.
@ffi.Native<ffi.Int32 Function()>()
external int amw_version();

/// Starts to create a virtual device from the specification spec
/// (spec_length bytes); the result follows as VIRTUAL_CREATED carrying
/// request and the handle of the device side, an AMW_KIND_VIRTUAL port.
/// Closing that handle removes the device.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<amw_context>,
    ffi.Int64,
    ffi.Pointer<ffi.Uint8>,
    ffi.Int32,
  )
>()
external int amw_virtual_create(
  ffi.Pointer<amw_context> context,
  int request,
  ffi.Pointer<ffi.Uint8> spec,
  int spec_length,
);

/// Starts the watchers of the AMW_SOURCE_* bits in sources. Each watcher
/// reports its ports with PORT_ADDED events and then ENUMERATION_COMPLETED,
/// or an ERROR event naming its source.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<amw_context>, ffi.Uint32)>()
external int amw_watch_start(ffi.Pointer<amw_context> context, int sources);

/// Stops all watchers.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<amw_context>)>()
external int amw_watch_stop(ffi.Pointer<amw_context> context);

const int AMW_BLE_CONNECTABLE = 1;

const int AMW_ENDPOINT_DISCOVERY_COMPLETE = 512;

const int AMW_ENDPOINT_HAS_IDENTITY = 32;

const int AMW_ENDPOINT_MULTI_CLIENT = 64;

const int AMW_ENDPOINT_RECEIVES_JR = 128;

const int AMW_ENDPOINT_STATIC_BLOCKS = 16;

const int AMW_ENDPOINT_SUPPORTS_MIDI1 = 1;

const int AMW_ENDPOINT_SUPPORTS_MIDI2 = 2;

const int AMW_ENDPOINT_SUPPORTS_RX_JR = 4;

const int AMW_ENDPOINT_SUPPORTS_TX_JR = 8;

const int AMW_ENDPOINT_TRANSMITS_JR = 256;

const int AMW_EVENT_BLE_ADVERTISEMENT = 8;

const int AMW_EVENT_BLE_PAIR_COMPLETED = 10;

const int AMW_EVENT_BLE_SCAN_STOPPED = 9;

const int AMW_EVENT_BLE_UNPAIR_COMPLETED = 11;

const int AMW_EVENT_ENUMERATION_COMPLETED = 4;

const int AMW_EVENT_ERROR = 13;

const int AMW_EVENT_EVENTS_DROPPED = 14;

const int AMW_EVENT_OPEN_COMPLETED = 6;

const int AMW_EVENT_PORT_ADDED = 1;

const int AMW_EVENT_PORT_DISCONNECTED = 7;

const int AMW_EVENT_PORT_REMOVED = 3;

const int AMW_EVENT_PORT_UPDATED = 2;

const int AMW_EVENT_VIRTUAL_CREATED = 12;

const int AMW_EVENT_WATCHER_STOPPED = 5;

const int AMW_E_ACCESS_DENIED = -2147024891;

const int AMW_E_BUFFER_TOO_SMALL = -1599275006;

const int AMW_E_CLOSED = -2147483629;

const int AMW_E_INVALID_ARGUMENT = -2147024809;

const int AMW_E_NOT_FOUND = -1599275001;

const int AMW_E_OUT_OF_MEMORY = -2147024882;

const int AMW_E_PORT_UNAVAILABLE = -1599275004;

const int AMW_E_SEND_FAILED = -1599275002;

const int AMW_E_SHUTTING_DOWN = -1599275000;

const int AMW_E_UNEXPECTED = -2147418113;

const int AMW_E_UNKNOWN_HANDLE = -1599275007;

const int AMW_E_UNSUPPORTED = -1599275005;

const int AMW_E_WRONG_KIND = -1599275003;

const int AMW_FEATURE_BLUETOOTH = 16;

const int AMW_FEATURE_MIDI1 = 1;

const int AMW_FEATURE_MIDI2 = 4;

const int AMW_FEATURE_MIDI2_BUILT = 2;

const int AMW_FEATURE_MIDI2_HYBRID = 8;

const int AMW_FEATURE_VIRTUAL_DEVICES = 32;

const int AMW_KIND_MIDI1_IN = 1;

const int AMW_KIND_MIDI1_OUT = 2;

const int AMW_KIND_MIDI2_IN = 3;

const int AMW_KIND_MIDI2_OUT = 4;

const int AMW_KIND_VIRTUAL = 5;

const int AMW_OK = 0;

const int AMW_PORT_ENABLED = 1;

const int AMW_RECORD_UMP = 1;

const int AMW_SOURCE_MIDI1_IN = 1;

const int AMW_SOURCE_MIDI1_OUT = 2;

const int AMW_SOURCE_MIDI2 = 4;

const int AMW_SOURCE_MIDI2_LOOPBACK = 8;

const int AMW_VERSION = 1;

const int AMW_VIRTUAL_MIDI2 = 2;

const int AMW_VIRTUAL_RECEIVE = 1;

/// A shim instance: its worker thread, watchers, ports and buffers.
final class amw_context extends ffi.Opaque {}

/// The function the shim calls when events or data are waiting. It must
/// return quickly and must not call back into the shim synchronously.
typedef amw_signal_fn = ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>;
